---
# Source: td-autoinject/templates/poddisruptionbudget.yaml
# yamllint disable
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-sidecar-injector
  namespace: istio-control
  labels:
    app: sidecar-injector
    release: istio-control-istio-autoinject
    istio: sidecar-injector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sidecar-injector
      release: istio-control-istio-autoinject
      istio: sidecar-injector

---
# Source: td-autoinject/templates/sidecar-injector-configmap.yaml
# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: istio-control
  labels:
    release: istio-control-istio-autoinject
    app: sidecar-injector
    istio: sidecar-injector
data:
  values: |-
    {"clusterResources":true,"global":{"arch":{"amd64":2,"ppc64le":2,"s390x":2},"configNamespace":"istio-control","configValidation":"false","controlPlaneSecurityEnabled":true,"defaultNodeSelector":{},"defaultPodDisruptionBudget":{"enabled":true},"defaultResources":{"requests":{"cpu":"10m"}},"disablePolicyChecks":true,"enableHelmTest":false,"enableTracing":true,"hub":"istio","imagePullPolicy":"Always","imagePullSecrets":[],"istioNamespace":"istio-control","k8sIngress":{"enableHttps":false,"enabled":false,"gatewayName":"ingressgateway"},"localityLbSetting":{"enabled":true},"logAsJson":false,"logging":{"level":"default:info"},"meshExpansion":{"enabled":false,"useILB":false},"meshID":"","meshNetworks":{},"mtls":{"enabled":false},"multiCluster":{"enabled":false},"oneNamespace":false,"outboundTrafficPolicy":{"mode":"ALLOW_ANY"},"policyCheckFailOpen":false,"policyNamespace":"istio-system","priorityClassName":"","prometheusNamespace":"istio-system","proxy":{"accessLogEncoding":"TEXT","accessLogFile":"","accessLogFormat":"","autoInject":"enabled","clusterDomain":"cluster.local","componentLogLevel":"misc:error","concurrency":2,"dnsRefreshRate":"300s","enableCoreDump":false,"envoyAccessLogService":{"enabled":false,"host":null,"port":null},"envoyMetricsService":{"enabled":false,"host":null,"port":null},"envoyStatsd":{"enabled":false,"host":null,"port":null},"excludeIPRanges":"","excludeInboundPorts":"","excludeOutboundPorts":"","image":"proxyv2","includeIPRanges":"*","includeInboundPorts":"*","kubevirtInterfaces":"","logLevel":"warning","privileged":false,"protocolDetectionTimeout":"10ms","readinessFailureThreshold":30,"readinessInitialDelaySeconds":1,"readinessPeriodSeconds":2,"resources":{"limits":{"cpu":"2000m","memory":"1024Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"statusPort":15020,"tag":"1.7.0","tracer":"zipkin"},"proxy_init":{"image":"proxyv2","resources":{"limits":{"cpu":"100m","memory":"50Mi"},"requests":{"cpu":"10m","memory":"10Mi"}}},"sds":{"enabled":false,"udsPath":""},"tag":"1.5.8","telemetryNamespace":"istio-system","tracer":{"datadog":{"address":"$(HOST_IP):8126"},"lightstep":{"accessToken":"","address":"","cacertPath":"","secure":true},"zipkin":{"address":""}},"trustDomain":"","useMCP":true,"xdsApiVersion":"v3"},"istio_cni":{"enabled":false},"sidecarInjectorWebhook":{"alwaysInjectSelector":[],"enableAccessLog":false,"enableNamespacesByDefault":false,"image":"sidecar_injector","injectLabel":"istio-injection","neverInjectSelector":[],"nodeSelector":{},"podAntiAffinityLabelSelector":[],"podAntiAffinityTermLabelSelector":[],"replicaCount":2,"rewriteAppHTTPProbe":false,"rollingMaxSurge":"100%","rollingMaxUnavailable":"25%","selfSigned":true,"tolerations":[]},"version":""}

  config: |-
    policy: enabled
    alwaysInjectSelector:
      []

    neverInjectSelector:
      []

    template: |
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.24.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: ENVOY_UID
          value: "1337"
        - name: ENVOY_GID
          value: "1337"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1337
          runAsGroup: 1337
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-bootstrap
        {{- if eq (annotation .ObjectMeta `cloud.google.com/enableManagedCerts` `false`) `true` }}
        - mountPath: /var/run/secrets/workload-spiffe-credentials
          name: gke-workload-certificates
          readOnly: true
        {{- end }}
      initContainers:
      - name: td-bootstrap-writer
        image: gcr.io/trafficdirector-prod/xds-client-bootstrap-generator:v0.1.0
        imagePullPolicy: Always
        args:
          - --project_number={{.ProxyConfig.ProxyMetadata.TRAFFICDIRECTOR_GCP_PROJECT_NUMBER}}
          - --network_name={{.ProxyConfig.ProxyMetadata.TRAFFICDIRECTOR_NETWORK_NAME}}
          {{- if (isset .ProxyConfig.ProxyMetadata `TRAFFICDIRECTOR_SCOPE_NAME`) }}
          - --scope_name={{.ProxyConfig.ProxyMetadata.TRAFFICDIRECTOR_SCOPE_NAME}}
          {{- end }}
          {{- if (isset .ProxyConfig.ProxyMetadata `TRAFFICDIRECTOR_MESH_NAME`) }}
          - --mesh_name={{.ProxyConfig.ProxyMetadata.TRAFFICDIRECTOR_MESH_NAME}}
          {{- end }}
          - --bootstrap_file_output_path=/var/lib/data/envoy.yaml
          - --traffic_director_url=trafficdirector.googleapis.com:443
          {{- if (isset .ObjectMeta.Annotations `cloud.google.com/includeInboundPorts`) }}
          - --inbound_backend_ports={{ (annotation .ObjectMeta `cloud.google.com/includeInboundPorts` ``) }}
          {{- end }}
          {{- if eq (annotation .ObjectMeta `cloud.google.com/forwardPodLabels` `false`) `true` }}
          - --proxy_metadata={{ toJSON .ObjectMeta.Labels }}
          {{- else if (isset .ObjectMeta.Annotations `cloud.google.com/proxyMetadata`) }}
          - |
              --proxy_metadata={{ (annotation .ObjectMeta `cloud.google.com/proxyMetadata` `{}`) }}
          {{- end }}
          {{- if eq (annotation .ObjectMeta `cloud.google.com/enableManagedCerts` `false`) `true` }}
          - --use_workload_certificates
          {{- end }}
          {{- if isset .ProxyConfig.ProxyMetadata `TRAFFICDIRECTOR_ACCESS_LOG_PATH` }}
          - --access_log_path={{.ProxyConfig.ProxyMetadata.TRAFFICDIRECTOR_ACCESS_LOG_PATH}}
          {{- end }}
          {{- if eq (valueOrDefault .ProxyConfig.ProxyMetadata.TRAFFICDIRECTOR_ENABLE_TRACING "") "true" }}
          - --enable_tracing
          {{- end }}
          - --envoy_admin_port={{.ProxyConfig.ProxyAdminPort}}
          {{- if isset .ProxyConfig.ProxyMetadata `PROXY_STATS_PORT` }}
          - --expose_stats_port={{.ProxyConfig.ProxyMetadata.PROXY_STATS_PORT}}
          {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1323
          runAsGroup: 1323
        volumeMounts:
          - mountPath: /var/lib/data
            name: envoy-bootstrap
      - name: istio-init
        image: istio/proxyv2:1.12.0
        imagePullPolicy: IfNotPresent
        args:
          - istio-iptables
          - -p
          - "15001"
          - -u
          - "1337"
          - -m
          - REDIRECT
          - -i
          - "{{ (annotation .ObjectMeta `cloud.google.com/includeOutboundCIDRs` `*`) }}"
          - -b
          - "{{ (annotation .ObjectMeta `cloud.google.com/includeInboundPorts` ``) }}"
          - -x
          - "{{ (annotation .ObjectMeta `cloud.google.com/excludeOutboundCIDRs` `169.254.169.254/32`) }}"
          - -d
          - "{{ (annotation .ObjectMeta `cloud.google.com/excludeInboundPorts` ``) }}"
          - -o
          - "{{ (annotation .ObjectMeta `cloud.google.com/excludeOutboundPorts` ``) }}"
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      volumes:
        - name: envoy-bootstrap
          emptyDir: {}
        {{- if eq (annotation .ObjectMeta `cloud.google.com/enableManagedCerts` `false`) `true` }}
        - name: gke-workload-certificates
          csi:
            driver: workloadcertificates.security.cloud.google.com
        {{- end }}
    ---



---
# Source: td-autoinject/templates/serviceaccount.yaml
# yamllint disable
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sidecar-injector-service-account
  namespace: istio-control
  labels:
    app: sidecar-injector
    release: istio-control-istio-autoinject
    istio: sidecar-injector

---
# Source: td-autoinject/templates/clusterrole.yaml
# yamllint disable
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-sidecar-injector-istio-control
  labels:
    app: sidecar-injector
    release: istio-control-istio-autoinject
    istio: sidecar-injector
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["istio-sidecar-injector"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  resourceNames: ["istio-sidecar-injector", "istio-sidecar-injector-istio-control"]
  verbs: ["get", "list", "watch", "patch"]

---
# Source: td-autoinject/templates/clusterrolebinding.yaml
# yamllint disable
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-sidecar-injector-admin-role-binding-istio-control
  labels:
    app: sidecar-injector
    release: istio-control-istio-autoinject
    istio: sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-sidecar-injector-istio-control
subjects:
  - kind: ServiceAccount
    name: istio-sidecar-injector-service-account
    namespace: istio-control

---
# Source: td-autoinject/templates/service.yaml
# yamllint disable
apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: istio-control
  labels:
    app: sidecar-injector
    release: istio-control-istio-autoinject
    istio: sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    istio: sidecar-injector

---
# Source: td-autoinject/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-sidecar-injector
  namespace: istio-control
  labels:
    app: sidecarInjectorWebhook
    release: istio-control-istio-autoinject
    istio: sidecar-injector
spec:
  replicas: 2
  selector:
    matchLabels:
      istio: sidecar-injector
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sidecarInjectorWebhook
        istio: sidecar-injector
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-sidecar-injector-service-account
      containers:
        - name: sidecar-injector-webhook
          image: "istio/sidecar_injector:1.5.8"
          imagePullPolicy: Always
          args:
            - --caCertFile=/etc/istio/certs/ca-cert.pem
            - --tlsCertFile=/etc/istio/certs/cert.pem
            - --tlsKeyFile=/etc/istio/certs/key.pem
            - --injectConfig=/etc/istio/inject/config
            - --meshConfig=/etc/istio/config/mesh
            - --port=9443
            - --healthCheckInterval=2s
            - --healthCheckFile=/tmp/health
            - --reconcileWebhookConfig=true
            - --webhookConfigName=istio-sidecar-injector-istio-control
            - --log_output_level=debug



          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
            readOnly: true
          - name: certs
            mountPath: /etc/istio/certs
            readOnly: true
          - name: inject-config
            mountPath: /etc/istio/inject
            readOnly: true
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/tmp/health
                - --interval=4s
            initialDelaySeconds: 4
            periodSeconds: 4
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/tmp/health
                - --interval=4s
            initialDelaySeconds: 4
            periodSeconds: 4
          resources:
            requests:
              cpu: 10m

      volumes:
      - name: config-volume
        configMap:
          name: injector-mesh
      - name: certs
        secret:
          secretName: istio-sidecar-injector
      - name: inject-config
        configMap:
          name: istio-sidecar-injector
          items:
          - key: config
            path: config
          - key: values
            path: values
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x

---
# Source: td-autoinject/templates/mutatingwebhook.yaml
# yamllint disable
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector-istio-control
  labels:
    app: sidecar-injector
    release: istio-control-istio-autoinject
webhooks:
  - name: sidecar-injector.istio.io
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: istio-control
        path: "/inject"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZmakNDQTJhZ0F3SUJBZ0lRZnVHVnVhS2g0c1dNeUtpMFM1Q25xakFOQmdrcWhraUc5dzBCQVFzRkFEQXoKTVRFd0x3WURWUVFERXlocGMzUnBieTF6YVdSbFkyRnlMV2x1YW1WamRHOXlMbWx6ZEdsdkxXTnZiblJ5YjJ3dQpjM1pqTUI0WERUSXpNREV3TmpBNU1EVXhNVm9YRFRJME1ERXdOakE1TURVeE1Wb3dNekV4TUM4R0ExVUVBeE1vCmFYTjBhVzh0YzJsa1pXTmhjaTFwYm1wbFkzUnZjaTVwYzNScGJ5MWpiMjUwY205c0xuTjJZekNDQWlJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBSzJaS3R6eXRRUXJ1Rm9TTUpEVmN5d0NxSTVGMnpCUApHL2NhV0tqeWdSa0FCK3FkNjk1OFkrRSt4WmdoejR4TUpLNlBKNFdKbTNpeWlUZiszZVQ1RzVTQnNCSmo0VWRaCkVWNSt4SG1ubDN4RXdUdU1pY2VUT3pUZHNOVHh5YW1YNVZXU3YvdWE2Z0htQTBWN2JsUFJHMmxsUDBCK1BmQjUKN2JqdmdCTFRlNGFSRXVKYVZ0VXM2elJ6T3NRQWhYYmQ5aHhKMEVCcFczeVdKRXN2OFhOaWRJazRvc0N1QUZXZgpEd3VLdU5tdUpTS1YrVktOdm1Ra0R3MnFvdWNtYVdrT25hY3VSODR5U2ZtaUxyNmk2bzY5a0tEMDk1cUs3dmw5ClhXaWgvVk1GSTlSR1lWYzJtTUVPbHo5SGE3aUthL1AvRjJFU2hCTW5RV1FGc1premVGYnA5MUhUdUp3VHArSUEKcENWa3d5ZDFuUGNiVkxWZEdJdkhXTUk1dksvTXc5QWpRd2FOY3dzM3hhVStadW9nZkg4cHc1Z3pUNitkYWxiQQp4cnRVVjdaZ3o2dnU1cXRjQy9hQnhKU0NhSE5tSVR1aVIvR2lyaTdYeWZ3QzRTcWRSdk1xWGpmc1FKdnJjN0dQClUyWTBEeDlmMlgxcnljajZXMlJhOGtDMDBxcnMxMVFWbWdIZURHVWcrVVUyTjVsK2ZXd28yNXlKSjczaGM2bnQKK1BTM1ZEUDRsbzJ6eHF2Qyt5UGNoTDNWRDBpRGJkNldJZ1FPb3c3RVZvRFF4ZjFPK3prRnFES0dkSWsrcVU0TQpVSFhDVVNHZVdpTzZRazhZRU0wNWNFRzFyMnhtN2EvdmJ6ci9BUklxNWkxWWlWTTZ2QmE3dkFMbFJ1aWp6SEZCCmt6eXowRmlYa1gxYkFnTUJBQUdqZ1kwd2dZb3dEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0cKQ0NzR0FRVUZCd01CTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRklQNUZwVlgvTGoxL0JrNApkMXJ1ZkZ4ZzFsV1JNRE1HQTFVZEVRUXNNQ3FDS0dsemRHbHZMWE5wWkdWallYSXRhVzVxWldOMGIzSXVhWE4wCmFXOHRZMjl1ZEhKdmJDNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUl4clBVZDVzVVJBU0FlMEtVUEkKU3dEUFBqKzhxNmlOM0xYRkNiTXVQYitCQzJnbnU1UkhnRmZsQldleEhCYkx1Q3dGOEtmZk9mdjQ1M2dPd1NuRApmaGdsT2JNaEVWdWREUjk2MTlhU1B2UG9KZGFaanUxN2cxbXJrMlRDWnJVY1E3dUcvYjZ2UUM2QjJJalJaSGJjCkRmcVZWZ1pwbTJVWjhpK3EzcWgxemVWeGxjMXRVZmgvRUJOTXRPbzNjOTRXSWpXdUY1ZGU4VHZ5cDE4L2RqelUKelByK1hlOWdxRC9DcWJqeGhJaVVNVGtEeGQ5YXJnNGhZREdCNjI4N0pYbDg5aXpFY3FUbFo3K3ZNMnpndTFIYQp5NklMSERtU0tady9uT2tRejE5U1JjUFF0UUVxdXJuVXo1OXRRbXF2RTFUZ3hTcG13VUlVUVltRWZWdFpYY0NYCmZLUlpLd0dEZy9RL29hQnAyeWFZdC9jRTgxRlFWSkNVWmtyUHJ2ZURqaEJMTGNUNUo0OGY1K3BxZ0I1ajZuK3IKYmZhTGI3NThlOEEvVU5NV0NDWEVkbDcyS2t5OGZoa1c4dklnTnUvOFE3KzQzRlRiQmROQXlNVjZGcnRWczY5SQpaYmVDR3MxOUpwMWYrY0lSZWR0ejZuak9FZ0pyUlczQzJVazNSZjRXd21yUGZJTUZNd1VNdDRaTWoxeDlpVWt0CjhRVTN1RkFPdCtRUExrSGs4MnRuUFhDTjZKMXdkZzFYTFpUZ3JYbFFXVlBjSW5LMU80UkV5VlJmckVZSGNEY0QKSWZnU2VlRFI4Z0wwT0VKZFM0am1YaUVLdnQyYjhpdWQzZzZ5ekdaZVB1NVFJL3BnYzlFQnA3V3lqMnVRRlJudQpjVitTdlpPbW1mSy8xNlpmZzVONkVLQm8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
---

